### ISSUE TITLE
overzicht leden

### ISSUE THREAD

**Issue by daanmaljaars** [MKS-Dashboard/mks-dashboard.github.io#169]
een overzicht van teamleden en andere spelers met bijv. aantal posten/voertuigen

**Comment by Piet2001** [comment]
Gegevens over posten en voertuigen van een persoon kunnen niet worden uitgelezen over andere spelers op basis van API.
Dit kan dus ook niet toegevoegd worden.

Info over teamgenoten staat al op de lijst onder suggestie #131
