### ISSUE TITLE
Cellen overzicht

### ISSUE THREAD

**Issue by Rene-63** [MKS-Dashboard/mks-dashboard.github.io#193]
Het overzicht van ziekenhuizen en hun bezetting per ziekenhuis is een ideaal hulpmiddel om regionaal bij te bouwen.
Is dit ook mogelijk voor cellen & cellencomplexen van het team?

**Comment by Piet2001** [comment]
Zou ik naar moeten kijken, maar ik verwacht dat het wel mogelijk is.

**Comment by Piet2001** [comment]
functie vergelijkbaar met #187 (Overzicht ziekenhuizen waar naar gerefereerd word in basis bericht)
