### ISSUE TITLE
Lijst van ziekenhuizen incl. bezetting sorteerbaar

### ISSUE THREAD

**Issue by Rene-63** [MKS-Dashboard/mks-dashboard.github.io#194]
De lijst van ziekenhuizen sorteer functie op bezette bedden en op naam

**Comment by Piet2001** [comment]
Overzicht in #187 gemaakt. En zou na mijn info al sorteerbaar moeten zijn door op de tabelkoppen te klikken. Als dit niet zo is hoor ik het graag.


Let op: functie momenteel nog Beta.

**Comment by Piet2001** [comment]
Al opgelost met #187
