### ISSUE TITLE
Menu balk --> hamburger menu

### ISSUE THREAD

**Issue by Rene-63** [MKS-Dashboard/mks-dashboard.github.io#210]
De menubalk zoals hij was (bovenin icoontjes) is prettiger dan met de 3 streepjes open klikken

**Comment by Piet2001** [comment]
De 3 streepjes komen als het scherm kleiner is dan een bepaalde grote. 
Dit is om er voor te zorgen dat het menu ook toegankelijk is op mobiele apparaten.

**Comment by Rene-63** [comment]
Wide-screen, halve scherm is dan te klein? 

⁣
Met vriendelijke groeten,

René Evertsen

Van Hoftenstraat 24
3815PP Amersfoort

Tel   :0626709104
Mail ***@***.***

​

Op 29 dec. 2022 18:31, om 18:31, Piet2001 ***@***.***> schreef:

**Comment by Piet2001** [comment]
Exacte maten durf ik niet te zeggen. 
Die zou ik moeten controleren. Volgens mij zijn dat de standaard bootstrap waardes nog.

**Comment by Piet2001** [comment]
momenteel lijkt het wisselpunt ergens rond de 990px te zitten

**Comment by Rene-63** [comment]
Voor mij is deze ok
