### ISSUE TITLE
Overzicht posten met specialistische uitbreiding (per specialisme)

### ISSUE THREAD

**Issue by Rene-63** [MKS-Dashboard/mks-dashboard.github.io#218]
Doelstelling, dat de speler zijn specialistische posten kan zien én met welk specialisme. Eigenlijk wat je nu doet door je specialistische posten onder een aparte meldkamer te plaatsen

**Comment by Piet2001** [comment]
Komt dat niet overeen met wat er al in zit, of begrijp ik het dan verkeerd.

![image](https://user-images.githubusercontent.com/54183168/212486176-854a3a4f-82b1-45c1-9e03-7d03e6f941bd.png)

**Comment by Rene-63** [comment]
Eeeeeeeh,

Voor iemand die er steeds naar kijkt, is het toch teleurstellend dit niet gezien te hebben 
Dit is het inderdaad

 

Met vriendelijke groeten,

 

René Evertsen

 

Van Hoftenstraat 24

3815PP Amersfoort

 

06-26709104

 

Van: Piet2001 ***@***.***> 
Verzonden: zaterdag 14 januari 2023 18:15
Aan: MKS-Dashboard/mks-dashboard.github.io ***@***.***>
CC: Rene-MKS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [MKS-Dashboard/mks-dashboard.github.io] Overzicht posten met specialistische uitbreiding (per specialisme) (Issue #218)

 

Komt dat niet overeen met wat er al in zit, of begrijp ik het dan verkeerd.

 <https://user-images.githubusercontent.com/54183168/212486176-854a3a4f-82b1-45c1-9e03-7d03e6f941bd.png>
